'use strict';
// Synthetic regression fixtures verify deterministic report behaviour, NOT real-world forecast accuracy.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const crypto = require('node:crypto');
const path = require('node:path');
const root=process.argv[2]||'/mnt/data/smv_v262/source';
const mod=require(path.join(root,'prediction-synthesis.js'));
const prev=require('/mnt/data/SMV_V258_changed/prediction-synthesis.js');
const names=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu'];
const domains=['career','jobchange','skills','turning','business','finance','marriage','children','education','property','debt','health','family','parents','siblings','travel','status','fortune','spiritual'];
const date='2026-10-10';
const taEn=(ta,en)=>({ta,en});
const house=(i,shift)=>({house:i,lord:names[(i+shift)%9],lordHouse:((i+2+shift)%12)+1,occupants:i<=9?[names[(i+shift-1)%9]]:[],state:['support','mixed','pressure'][(i-1)%3],supportAspects:i%2?['Jupiter']:[],pressureAspects:i%3?['Saturn']:[],neutralAspects:[],planetReadings:{},rulerCondition:{dignityKnown:true,exalted:false,ownSign:i===3,moolatrikona:false,debilitated:i===8,ratio:1.05},assessment:{varga:[{n:9,state:(i+shift)%2?'support':'mixed',testedPlanets:['Jupiter']}],support:[],pressure:[]}});
const planetPos=(i,shift)=>({planet:names[i],longitude:((i*33+shift*7)%360),signIndex:Math.floor(((i*33+shift*7)%360)/30),degreeInSign:((i*33+shift*7)%30),house:((i+shift)%12)+1,signHouse:((i+shift)%12)+1,ownedHouses:[((i+shift)%12)+1],retrograde:false,basis:'calculated-bhava'});
const domain=(id,i,shift)=>({id,house:((i+2)%12)+1,lord:names[(i+shift)%9],lordHouse:((i+2+shift)%12)+1,occupants:i%2?[names[(i+shift)%9]]:[],state:i%2?'pressure':'support',events:taEn([`சோதனை முடிவு ${id}`],[`Synthetic outcome ${id}`]),eventIds:[],fields:taEn([],[]),depth:taEn([],[]),varga:9,vargaAvailable:i%2===0,vargaStrength:i%3-1,timing:i===0?{best:{start:'2026-09-01',end:'2026-12-31',event:taEn('பொறுப்பு மாறுதல்','a change in responsibilities')}}:null});
function horo(shift=0,age=34){return {referenceDate:date,context:{age,work:'business',marital:'married',residence:'Perambalur',birthPlace:'Perambalur'},positions:names.map((_,i)=>planetPos(i,shift)),houses:Array.from({length:12},(_,j)=>house(j+1,shift)),domains:domains.map((id,i)=>domain(id,i,shift)),dashas:[{start:'2026-01-01',end:'2027-01-01',md:names[shift%9],ad:names[(shift+1)%9],age,priorities:[{title:taEn('தொழில்','Career'),event:taEn('பணி மாறலாம்','Role could change'),state:'mixed'}]}],transits:[{planet:'Jupiter',house:(shift%12)+1,start:'2026-01-01',end:'2026-12-31',age,meaning:taEn('வழிகாட்டல்','guidance'),focus:taEn('தொழில்','career')}],timeline:[],capacity:{}}}
function profile(i,shift,who){const o=(who==='b'?1:3);return {layers:[{division:'D1',houses:[{house:((i+o)%12)+1,lord:names[(i+shift+o)%9],lordHouse:((i+shift+o)%12)+1,lordSignIndex:(i+shift)%12,occupants:[names[(i+o)%9]]}]},{division:'D9',houses:[{house:((i+o)%12)+1,lord:names[(i+shift+o+2)%9],lordHouse:((i+shift+o+4)%12)+1,lordSignIndex:(i+shift+2)%12,occupants:[]}]}]};}
function match(shift=0){const topics=Array.from({length:25},(_,i)=>({index:i+1,titleEn:`Married life topic ${i+1}`,titleTa:`திருமண வாழ்க்கை தலைப்பு ${i+1}`,brideScore:(i+shift)%5-1,groomScore:(i+shift*2)%6-2,state:['mutual','pressure','asym','mixed'][(i+shift)%4],supportReading:taEn(`இணை ஆதாரம் ${i+1}`,`Joint support ${i+1}`),careReading:taEn(`சிரமம் ${i+1}`,`Care ${i+1}`),guidance:taEn(`பகுதி ${i+1} குறித்து பேசுங்கள்`,`Discuss ${i+1}`),brideProfile:profile(i,shift,'b'),groomProfile:profile(i,shift,'g')}));return {referenceDate:date,brideBirthDate:'1994-06-15',groomBirthDate:'1992-07-31',poruthamGood:6,poruthamTotal:10,brideBalance:1,groomBalance:-2,topics,clusters:[],timing:[],verdict:taEn('ஆலோசனை தேவை','CONSULTATION NEEDED')}}

const results={version:mod.VERSION,checks:[],stress:{},scope:'Structural fixtures, not actual forecast accuracy'};
function check(name,fn){try{fn();results.checks.push({name,pass:true});}catch(e){results.checks.push({name,pass:false,error:String(e.stack||e).slice(0,900)});}}
check('V262 local deterministic synthesis',()=>{assert.equal(mod.VERSION,'smv-deterministic-synthesis-v263');const a=mod.synthesize('horoscope',horo());assert.equal(a.nonAI,true);assert.equal(a.engine,mod.VERSION)});
check('Both copies of synthesis match',()=>assert.equal(fs.readFileSync(path.join(root,'prediction-synthesis.js'),'utf8'),fs.readFileSync(path.join(root,'public/horoscope/prediction-synthesis.js'),'utf8')));
check('Browser and Node synthesis agree',()=>{const c={Date,globalThis:null};c.globalThis=c;vm.runInNewContext(fs.readFileSync(path.join(root,'public/horoscope/prediction-synthesis.js'),'utf8'),c);assert.equal(c.SMVPredictionSynthesis.VERSION,mod.VERSION);assert.equal(JSON.stringify(c.SMVPredictionSynthesis.synthesize('horoscope',horo())),JSON.stringify(mod.synthesize('horoscope',horo())))});
check('EN and TA preserve 12 house charts',()=>{for(const age of [2,14,34,72]){const a=mod.synthesize('horoscope',horo(3,age));for(const lang of ['en','ta'])assert.equal(a[lang].life.filter(x=>Number.isInteger(x.house)&&x.house>=1&&x.house<=12).length,12)}});
check('EN and TA preserve 25 marriage topics',()=>{const a=mod.synthesize('matching',match());for(const lang of ['en','ta'])assert.deepEqual(a[lang].topics.map(x=>x.index),Array.from({length:25},(_,i)=>i+1))});
check('D1 + D9 are evidence-labeled per marriage topic',()=>{const m=mod.synthesize('matching',match());for(const lang of ['ta','en'])for(const t of m[lang].topics){const s=t.paragraphs.join(' ');assert(s.includes('D1')&&s.includes('D9'))}});
check('Missing D1/D9 profile not treated as full individual finding',()=>{const v=match();v.topics[0].brideProfile={layers:[{division:'D1',houses:[]}]};v.topics[0].brideScore=null;const r=mod.synthesize('matching',v).en.topics[0].paragraphs.join(' ');assert(r.includes('incomplete'));assert(r.includes('score is not enough'));assert(!r.includes('bride 0.00'))});
check('Different planetary positions give differing narratives',()=>{assert.notEqual(mod.synthesize('horoscope',horo(0)).ta.life[0].paragraphs.join(' '),mod.synthesize('horoscope',horo(5)).ta.life[0].paragraphs.join(' '))});
check('Life chapters preserve astro-specific position context',()=>{const r=mod.synthesize('horoscope',horo()).ta.life;assert(r[0].paragraphs.join(' ').includes('பாவ அதிபதி'))});
check('Active MD AD are stated in timing',()=>{const r=mod.synthesize('horoscope',horo());const p=r.ta.timing.phases.flatMap(x=>x.paragraphs).join(' ');assert(p.includes('மகாதசை'));assert(p.includes('புக்தி'))});
check('No dasha means no domain-specific timing promises',()=>{const v=horo();v.dashas=[];const r=mod.synthesize('horoscope',v);assert(!r.en.timing.areas.some(x=>x.id==='career'))});
check('Dasha domain rows require natal links',()=>{const v=horo();v.dashas=[{start:'2026-01-01',end:'2026-10-30',md:'none',ad:'none',age:34,priorities:[{id:'career',event:taEn('பணி','role'),state:'support',title:taEn('வேலை','Career')}]}];const r=mod.synthesize('horoscope',v);assert(r.en.timing.phases[0].paragraphs.join(' ').includes('not asserted'));assert(!r.en.timing.areas.some(x=>x.id==='career'))});
check('Multiple same-house transits consolidated not 5 repeated paragraphs',()=>{const v=horo();v.transits=[...Array(5)].map((_,i)=>({planet:'Jupiter',house:1,start:`2026-0${i+1}-01`,end:`2026-0${i+1}-20`,meaning:taEn('வாய்ப்பு','opportunity')}));const r=mod.synthesize('horoscope',v);const q=r.en.timing.areas.find(x=>x.title.startsWith('Jupiter transit'));assert(q);assert(q.paragraphs.length<=2);assert(q.paragraphs.join(' ').includes('Repeated windows'))});
check('Child charts avoid adult house interpretations',()=>{for(const age of [2,14]){const r=mod.synthesize('horoscope',horo(0,age));for(const lang of ['en','ta']){assert.equal(r[lang].life.filter(x=>Number.isInteger(x.house)).length,12);assert(!r[lang].life.filter(x=>x.house).some(x=>x.sections?.some(y=>y.title==='Main life interpretation')))}}});
check('Elder life-stage lens present',()=>{const r=mod.synthesize('horoscope',horo(0,72));assert(r.en.life.some(x=>x.paragraphs.join(' ').includes('later life stage')))});
check('Tamil common English leakage tokens translated',()=>{const r=mod.synthesize('horoscope',horo());const s=r.ta.life.flatMap(x=>x.paragraphs).join(' ');assert(!/\b(?:mentor|client|routine|formal|capacity|project|portfolio|practice|skill)\b/i.test(s))});
check('Offline current dasha lookup no nulls in three real ephemeris charts',()=>{for(let i=1;i<=3;i++){const c=JSON.parse(fs.readFileSync('/mnt/data/smv_v262/chart_'+i+'.json','utf8')).result.chart.dashas.current;assert.equal(c.referenceDate,'2026-10-10');for(const k of ['mahadasha','antardasha','pratyantardasha']){assert(c[k]?.lord&&c[k].start<=c.referenceDate&&c.referenceDate<c[k].end)}}});
check('Original V261 planetary calculations not edited',()=>{for(const f of ['swiss_vedic.js','public/horoscope/offline/swiss_vedic.browser.mjs']){const a=fs.readFileSync(path.join(root,f));const b=fs.readFileSync('/mnt/data/smv_v261/source/'+f);assert(a.equals(b),f)}});
check('V260 admin/off pricing untouched',()=>{for(const f of ['server.js','public/horoscope/config.js']){const a=fs.readFileSync(path.join(root,f));const b=fs.readFileSync('/mnt/data/smv_v261/source/'+f);assert(a.equals(b),f)}});
check('Auth, saved PDF, PWA, quota-related files remain untouched',()=>{for(const f of ['public/horoscope/horoscope-auth.mjs','public/horoscope/report-store.mjs','public/horoscope/report-print.js','public/horoscope/sw.js','public/horoscope/marriage-matching.js']){assert(fs.readFileSync(path.join(root,f)).equals(fs.readFileSync('/mnt/data/smv_v261/source/'+f)),f)}});
check('Prediction evidence change scoped to active current-period field',()=>{const f='public/horoscope/horoscope-predictions.js';const now=fs.readFileSync(path.join(root,f),'utf8');const before=fs.readFileSync('/mnt/data/smv_v261/source/'+f,'utf8');assert.equal(now.replace(',currentPeriod:c?.dashas?.current||null',''),before)});
check('Client API uses V262 local synthesis and busts stale IndexedDB version',()=>{const j=fs.readFileSync(path.join(root,'public/horoscope/prediction-online.js'),'utf8'),html=fs.readFileSync(path.join(root,'public/horoscope/index.html'),'utf8');assert(j.includes('v263-non-ai')&&j.includes('smv-deterministic-synthesis-v263'));assert(html.includes('prediction-synthesis.js?v=263')&&html.includes('prediction-online.js?v=263'))});
check('Client HTML retains exactly 25 marriage topics',()=>{const c={window:{SMV_BACKEND_URL:''},Date,TextEncoder,AbortController,setTimeout,clearTimeout,globalThis:null};c.globalThis=c;vm.runInNewContext(fs.readFileSync(path.join(root,'public/horoscope/prediction-online.js'),'utf8'),c);const m=mod.synthesize('matching',match());for(const lang of ['en','ta']){const html=c.window.SMVPredictionOnline.matchingHtml(m,lang);assert.equal((html.match(/class="mm-human-topic"/g)||[]).length,25)}});
check('No LLM or extra network in synthesis',()=>assert(!/\b(fetch|XMLHttpRequest|openai\.com|chat\.completions\.create)\s*\(/.test(fs.readFileSync(path.join(root,'prediction-synthesis.js'),'utf8'))));
check('Deterministic with identical evidence',()=>assert.deepEqual(mod.synthesize('horoscope',horo(1)),mod.synthesize('horoscope',horo(1))));
check('Current MD/AD/PD chapter reads only validated chart evidence',()=>{const record=JSON.parse(fs.readFileSync('/mnt/data/smv_v262/horoscope_report_1.json','utf8'));const e=record.evidence;const a=mod.synthesize('horoscope',e);for(const lang of ['ta','en']){const chapter=a[lang].timing.areas.find(x=>x.id==='active-md-ad-pd');assert(chapter);assert(chapter.paragraphs.join(' ').includes('2026-10-10'));assert(chapter.provenance.pd==='Venus')}const wrong=JSON.parse(JSON.stringify(e));wrong.currentPeriod.referenceDate='2026-10-09';const b=mod.synthesize('horoscope',wrong);assert(!b.ta.timing.areas.some(x=>x.id==='active-md-ad-pd'));});
let hpass=0,mpass=0,errors=[];for(let i=0;i<100;i++){try{const a=mod.synthesize('horoscope',horo(i%9,[2,14,24,34,72][i%5]));for(const lang of ['ta','en'])assert.equal(a[lang].life.filter(x=>Number.isInteger(x.house)).length,12);hpass++;const m=mod.synthesize('matching',match(i));for(const lang of ['ta','en'])assert.equal(m[lang].topics.length,25);mpass++;}catch(e){errors.push({i,error:String(e)})}}
results.stress={syntheticHoroscopes:hpass,syntheticMatching:mpass,errors};
results.passCount=results.checks.filter(c=>c.pass).length;results.failCount=results.checks.filter(c=>!c.pass).length;
const outfile='/mnt/data/smv_v263/regression_results.json';fs.writeFileSync(outfile,JSON.stringify(results,null,2));console.log(JSON.stringify({passCount:results.passCount,failCount:results.failCount,failures:results.checks.filter(x=>!x.pass),stress:results.stress},null,2));if(results.failCount||errors.length)process.exitCode=1;
