plugins { id "com.android.application" }

android {
    namespace "in.smvastroservices.horoscope.test"
    compileSdk 36

    defaultConfig {
        applicationId "in.smvastroservices.horoscope.test"
        minSdk 24
        targetSdk 36
        versionCode 4
        versionName "1.0.3-test-standalone-ui"
    }

    buildTypes {
        debug {
            applicationIdSuffix ""
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
        }
    }
}
